services:
  server:
    build:
      context: .
    ports:
      - "8000:8000"

    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      - REDIS_HOST=redis-stack-test
      - REDIS_PORT=6379
      - REDIS_USER=${REDIS_USER:-default}
      - REDIS_PASSWORD=${REDIS_PASSWORD}

    depends_on:
      db:
        condition: service_healthy
      redis-stack-test:
        condition: service_healthy
  db:
     image: mirror.gcr.io/postgres
     restart: always
     user: postgres
     volumes:
       - db-data:/var/lib/postgresql/data
     environment:
       - POSTGRES_DB=${DB_NAME}
       - POSTGRES_USER=${DB_USER}
       - POSTGRES_PASSWORD=${DB_PASSWORD}
     expose:
       - "5432"
     healthcheck:
       test: [ "CMD", "pg_isready" ]
       interval: 10s
       timeout: 5s
       retries: 5

  redis-stack-test:
    image: redis/redis-stack-server:latest
    container_name: redis_stack_for_tests
    restart: always
    environment:
      - REDIS_ARGS=--requirepass ${REDIS_PASSWORD}
    expose:
      - "6379"
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli -a \"$REDIS_PASSWORD\" ping | grep PONG" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # Добавление отдельного сервиса для запуска тестов
  tests:
    build:
      context: .
    volumes:
      - .:/app
    # Сервис тестов зависит от DB и Redis Stack
    depends_on:
      db:
        condition: service_healthy
      redis-stack-test:
        condition: service_healthy

    # Наследуем настройки окружения для подключения к DB и Redis Stack
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_PORT=5432
      # Используем имя сервиса Redis Stack
      - REDIS_HOST=redis-stack-test
      - REDIS_PORT=6379
      - REDIS_PASSWORD=${REDIS_PASSWORD}

    # Команда будет задаваться при запуске (см. ниже)
    entrypoint: ["/usr/local/bin/poetry", "run", "pytest"]

volumes:
   db-data:

