"""create question bank tables

Revision ID: 37b322404fd9
Revises: ce387662b1e7
Create Date: 2026-01-28 06:57:58.434539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '37b322404fd9'
down_revision: Union[str, Sequence[str], None] = 'ce387662b1e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    table_names = set(inspector.get_table_names())

    # ### commands auto generated by Alembic - please adjust! ###
    if "categories" not in table_names:
        op.create_table('categories',
        sa.Column('category', sa.String(), nullable=False),
        sa.Column('parent_id', sa.UUID(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['parent_id'], ['categories.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('category')
        )
        table_names.add("categories")

    if "permissions" not in table_names:
        op.create_table('permissions',
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        table_names.add("permissions")

    if "regions" not in table_names:
        op.create_table('regions',
        sa.Column('region', sa.String(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        table_names.add("regions")
    if "regions" in table_names:
        region_indexes = {
            tuple(index["column_names"])
            for index in inspector.get_indexes("regions")
            if index.get("unique")
        }
        region_uniques = {
            tuple(constraint["column_names"])
            for constraint in inspector.get_unique_constraints("regions")
        }
        if ("region",) not in region_indexes and ("region",) not in region_uniques:
            op.create_index('regions_region_key', 'regions', ['region'], unique=True)

    if "roles" not in table_names:
        op.create_table('roles',
        sa.Column('role', sa.String(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.PrimaryKeyConstraint('id')
        )
        table_names.add("roles")

    if "role2permission" not in table_names:
        op.create_table('role2permission',
        sa.Column('role_id', sa.UUID(), nullable=False),
        sa.Column('permission_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
        sa.PrimaryKeyConstraint('role_id', 'permission_id')
        )
        table_names.add("role2permission")

    if "settlements" not in table_names:
        op.create_table('settlements',
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('type', sa.String(), nullable=False),
        sa.Column('region_id', sa.UUID(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['region_id'], ['regions.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        table_names.add("settlements")
    if "settlements" in table_names:
        settlement_indexes = {
            tuple(index["column_names"])
            for index in inspector.get_indexes("settlements")
            if index.get("unique")
        }
        settlement_uniques = {
            tuple(constraint["column_names"])
            for constraint in inspector.get_unique_constraints("settlements")
        }
        if ("name", "type", "region_id") not in settlement_indexes and ("name", "type", "region_id") not in settlement_uniques:
            op.create_index('settlements_natural_key', 'settlements', ['name', 'type', 'region_id'], unique=True)

    if "schools" not in table_names:
        op.create_table('schools',
        sa.Column('full_name', sa.String(), nullable=False),
        sa.Column('short_name', sa.String(), nullable=True),
        sa.Column('city_id', sa.UUID(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['city_id'], ['settlements.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        table_names.add("schools")

    if "users" not in table_names:
        op.create_table('users',
        sa.Column('full_name', sa.String(), nullable=False),
        sa.Column('nickname', sa.String(), nullable=False),
        sa.Column('age', sa.Integer(), nullable=False),
        sa.Column('email', sa.String(), nullable=True),
        sa.Column('phone_number', sa.String(), nullable=True),
        sa.Column('password', sa.String(), nullable=False),
        sa.Column('school_id', sa.UUID(), nullable=True),
        sa.Column('role_id', sa.UUID(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
        sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('phone_number')
        )
        table_names.add("users")

    if "questions" not in table_names:
        op.create_table('questions',
        sa.Column('text', sa.String(), nullable=False),
        sa.Column('teacher_id', sa.UUID(), nullable=False),
        sa.Column('category_id', sa.UUID(), nullable=True),
        sa.Column('question_type', sa.Enum('single', 'multiple', 'text', name='question_type_enum'), nullable=False),
        sa.Column('problem', sa.Text(), nullable=False),
        sa.Column('answer', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column('market_out_of', sa.Integer(), nullable=False),
        sa.Column('penalty', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
        sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        table_names.add("questions")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    table_names = set(inspector.get_table_names())

    # ### commands auto generated by Alembic - please adjust! ###
    if "questions" in table_names:
        op.drop_table('questions')
    if "users" in table_names:
        op.drop_table('users')
    if "schools" in table_names:
        op.drop_table('schools')
    if "settlements" in table_names:
        settlement_indexes = {index["name"] for index in inspector.get_indexes("settlements")}
        if "settlements_natural_key" in settlement_indexes:
            op.drop_index('settlements_natural_key', table_name='settlements')
        op.drop_table('settlements')
    if "role2permission" in table_names:
        op.drop_table('role2permission')
    if "roles" in table_names:
        op.drop_table('roles')
    if "regions" in table_names:
        region_indexes = {index["name"] for index in inspector.get_indexes("regions")}
        if "regions_region_key" in region_indexes:
            op.drop_index('regions_region_key', table_name='regions')
        op.drop_table('regions')
    if "permissions" in table_names:
        op.drop_table('permissions')
    if "categories" in table_names:
        op.drop_table('categories')
    # ### end Alembic commands ###
