"""United first, second and middle names into one fullname. Added nicknames

Revision ID: 6774e4958560
Revises: f24f2436b9c9
Create Date: 2025-10-31 07:56:09.430227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6774e4958560'
down_revision: Union[str, Sequence[str], None] = 'f24f2436b9c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_index(op.f('settlements_natural_key'), table_name='settlements')
    # op.create_unique_constraint(None, 'settlements', ['name'])
    # 1) Add as NULLable, so we can fill values first
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))

    # 2) Populate from existing parts, avoiding double spaces
    #    concat_ws skips NULLs/empty parts; trim removes accidental surrounding spaces
    op.execute(
        """
        UPDATE users
        SET full_name = trim(both FROM concat_ws(' ', NULLIF(first_name,''), NULLIF(middle_name,''), NULLIF(second_name,'')));
        """
    )

    # 3) Enforce NOT NULL now that data is copied
    op.alter_column('users', 'full_name', nullable=False)

    # 4) Drop old columns
    op.drop_column('users', 'middle_name')
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'second_name')

    # 5) Add nicknames column if you want it now (array of strings, empty by default)
    #    Remove this block if `nicknames` is added in a separate migration
    op.add_column('users', sa.Column('nicknames', sa.ARRAY(sa.String()), server_default=sa.text("'{}'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Recreate old columns as NULLable first to backfill
    op.add_column('users', sa.Column('second_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('middle_name', sa.VARCHAR(), autoincrement=False, nullable=True))

    # Best-effort split of full_name: first token -> first_name, last token -> second_name, middle -> middle_name
    op.execute(
        """
        UPDATE users u
        SET
          first_name  = COALESCE( (regexp_split_to_array(u.full_name, '\\s+'))[1], '' ),
          second_name = COALESCE( (regexp_split_to_array(u.full_name, '\\s+'))[array_length(regexp_split_to_array(u.full_name, '\\s+'), 1)], '' ),
          middle_name = CASE
              WHEN array_length(regexp_split_to_array(u.full_name, '\\s+'), 1) >= 3 THEN (regexp_split_to_array(u.full_name, '\\s+'))[2]
              ELSE ''
          END
        ;
        """
    )

    # Enforce NOT NULL to match the previous schema
    op.alter_column('users', 'first_name', nullable=False)
    op.alter_column('users', 'second_name', nullable=False)
    op.alter_column('users', 'middle_name', nullable=False)

    # Drop new columns
    op.drop_column('users', 'full_name')
    # Drop nicknames if it exists in this revision
    op.drop_column('users', 'nicknames')
    # op.drop_constraint(None, 'settlements', type_='unique')
    # op.create_index(op.f('settlements_natural_key'), 'settlements', ['name', 'type', 'region_id'], unique=True)
    # ### end Alembic commands ###
