"""United first, second and middle names into one fullname. Added nicknames

Revision ID: a319487c85c2
Revises: f24f2436b9c9
Create Date: 2025-10-31 08:19:11.533317

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a319487c85c2'
down_revision: Union[str, Sequence[str], None] = 'f24f2436b9c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # 1) Add as NULLable, so we can fill values first
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.add_column('users', sa.Column('nickname', sa.String(), nullable=True))

    # 2) Populate full_name from existing parts; concat_ws skips NULL/empty, trim removes extra spaces
    op.execute(
        """
        UPDATE users
        SET full_name = trim(both FROM concat_ws(' ', NULLIF(first_name,''), NULLIF(middle_name,''), NULLIF(second_name,'')));
        """
    )

    # Optionally backfill nickname: use the first token of full_name (fallback empty string)
    op.execute(
        """
        UPDATE users
        SET nickname = COALESCE(NULLIF(split_part(full_name, ' ', 1), ''), '')
        WHERE nickname IS NULL;
        """
    )

    # 3) Enforce NOT NULL now that data is copied
    op.alter_column('users', 'full_name', nullable=False)
    op.alter_column('users', 'nickname', nullable=False)

    # 4) Drop old columns
    op.drop_column('users', 'middle_name')
    op.drop_column('users', 'second_name')
    op.drop_column('users', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # Recreate old columns as NULLable first to backfill
    op.add_column('users', sa.Column('first_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('middle_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('second_name', sa.VARCHAR(), autoincrement=False, nullable=True))

    # Best-effort split of full_name: first token -> first_name, last token -> second_name, middle -> middle_name
    op.execute(
        """
        UPDATE users u
        SET
          first_name  = COALESCE( (regexp_split_to_array(u.full_name, '\\s+'))[1], '' ),
          second_name = COALESCE( (regexp_split_to_array(u.full_name, '\\s+'))[array_length(regexp_split_to_array(u.full_name, '\\s+'), 1)], '' ),
          middle_name = CASE
              WHEN array_length(regexp_split_to_array(u.full_name, '\\s+'), 1) >= 3 THEN (regexp_split_to_array(u.full_name, '\\s+'))[2]
              ELSE ''
          END
        ;
        """
    )

    # Enforce NOT NULL to match the previous schema
    op.alter_column('users', 'first_name', nullable=False)
    op.alter_column('users', 'middle_name', nullable=False)
    op.alter_column('users', 'second_name', nullable=False)

    # Drop new columns
    op.drop_column('users', 'nickname')
    op.drop_column('users', 'full_name')
