"""Align indexes with manual DB: regions_region_key, settlements_natural_key

Revision ID: ce387662b1e7
Revises: a319487c85c2
Create Date: 2025-10-31 08:24:12.761309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce387662b1e7'
down_revision: Union[str, Sequence[str], None] = 'a319487c85c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('regions_region_key'), 'regions', type_='unique')
    op.create_index('regions_region_key', 'regions', ['region'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('regions_region_key', table_name='regions')
    op.create_unique_constraint(op.f('regions_region_key'), 'regions', ['region'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
