"""Align indexes with manual DB: regions_region_key, settlements_natural_key

Revision ID: ce387662b1e7
Revises: a319487c85c2
Create Date: 2025-10-31 08:24:12.761309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce387662b1e7'
down_revision: Union[str, Sequence[str], None] = 'a319487c85c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    table_names = set(inspector.get_table_names())

    # ### commands auto generated by Alembic - please adjust! ###
    if "regions" in table_names:
        region_uniques = [
            constraint
            for constraint in inspector.get_unique_constraints("regions")
            if tuple(constraint["column_names"]) == ("region",)
        ]
        for constraint in region_uniques:
            op.drop_constraint(constraint["name"], "regions", type_="unique")

        region_indexes = {
            tuple(index["column_names"])
            for index in inspector.get_indexes("regions")
            if index.get("unique")
        }
        if ("region",) not in region_indexes:
            op.create_index('regions_region_key', 'regions', ['region'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    table_names = set(inspector.get_table_names())

    # ### commands auto generated by Alembic - please adjust! ###
    if "regions" in table_names:
        region_indexes = {index["name"] for index in inspector.get_indexes("regions")}
        if "regions_region_key" in region_indexes:
            op.drop_index('regions_region_key', table_name='regions')

        region_uniques = {
            tuple(constraint["column_names"])
            for constraint in inspector.get_unique_constraints("regions")
        }
        if ("region",) not in region_uniques:
            op.create_unique_constraint(
                op.f('regions_region_key'),
                'regions',
                ['region'],
                postgresql_nulls_not_distinct=False,
            )
    # ### end Alembic commands ###
