"""Added unique constraints to settlements and regions

Revision ID: f24f2436b9c9
Revises: 033282907fb3
Create Date: 2025-10-17 08:07:23.484574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f24f2436b9c9'
down_revision: Union[str, Sequence[str], None] = '033282907fb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'regions', ['region'])
    op.alter_column('schools', 'short_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'settlements', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'settlements', type_='unique')
    op.alter_column('schools', 'short_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'regions', type_='unique')
    # ### end Alembic commands ###
