"""Added unique constraints to settlements and regions

Revision ID: f24f2436b9c9
Revises: 033282907fb3
Create Date: 2025-10-17 08:07:23.484574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f24f2436b9c9'
down_revision: Union[str, Sequence[str], None] = '033282907fb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    table_names = set(inspector.get_table_names())

    # ### commands auto generated by Alembic - please adjust! ###
    if "regions" in table_names:
        region_uniques = {
            tuple(constraint["column_names"])
            for constraint in inspector.get_unique_constraints("regions")
        }
        region_indexes = {
            tuple(index["column_names"])
            for index in inspector.get_indexes("regions")
            if index.get("unique")
        }
        if ("region",) not in region_uniques and ("region",) not in region_indexes:
            op.create_unique_constraint(None, "regions", ["region"])

    if "schools" in table_names:
        school_columns = {col["name"] for col in inspector.get_columns("schools")}
        if "short_name" in school_columns:
            op.alter_column(
                "schools",
                "short_name",
                existing_type=sa.VARCHAR(),
                nullable=True,
            )

    if "settlements" in table_names:
        settlement_uniques = {
            tuple(constraint["column_names"])
            for constraint in inspector.get_unique_constraints("settlements")
        }
        settlement_indexes = {
            tuple(index["column_names"])
            for index in inspector.get_indexes("settlements")
            if index.get("unique")
        }
        if ("name",) not in settlement_uniques and ("name",) not in settlement_indexes:
            op.create_unique_constraint(None, "settlements", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    table_names = set(inspector.get_table_names())

    # ### commands auto generated by Alembic - please adjust! ###
    if "settlements" in table_names:
        settlement_uniques = [
            constraint
            for constraint in inspector.get_unique_constraints("settlements")
            if tuple(constraint["column_names"]) == ("name",)
        ]
        for constraint in settlement_uniques:
            op.drop_constraint(constraint["name"], "settlements", type_="unique")

    if "schools" in table_names:
        school_columns = {col["name"] for col in inspector.get_columns("schools")}
        if "short_name" in school_columns:
            op.alter_column(
                "schools",
                "short_name",
                existing_type=sa.VARCHAR(),
                nullable=False,
            )

    if "regions" in table_names:
        region_uniques = [
            constraint
            for constraint in inspector.get_unique_constraints("regions")
            if tuple(constraint["column_names"]) == ("region",)
        ]
        for constraint in region_uniques:
            op.drop_constraint(constraint["name"], "regions", type_="unique")
    # ### end Alembic commands ###
